# -*- coding: utf-8 -*-
"""Тексты сайта darsa.kz на трёх языках. Правим здесь, потом `python build.py`."""

PHONE = "+7 701 950 02 52"
PHONE_HREF = "tel:+77019500252"
BIN = "260940002289"
ORIGIN = "https://darsa.kz"

LANGS = [
    ("ru", "", "RU"),
    ("kk", "kk/", "ҚАЗ"),
    ("en", "en/", "EN"),
]

C = {}

# --------------------------------------------------------------------------- RU
C["ru"] = {
    "title": "Darsa Solutions — iDüken, ToiApp, Bota",
    "desc": "ТОО «DARSA Solutions»: iDüken — касса и склад магазина, ToiApp — всё для тоя в вашем городе, Bota — ИИ-агент внутри 1С. Казахстан, тенге, казахский и русский.",
    "og_title": "Darsa Solutions — программы для бизнеса в Казахстане",
    "og_desc": "Касса и склад магазина, поиск всего для тоя, ИИ-агент в 1С.",
    "og_locale": "ru_RU",
    "skip": "К содержанию",
    "nav_label": "Разделы",
    "nav_faq": "Вопросы",
    "nav_call": "Позвонить",
    "lang_label": "Язык",
    "theme_label": "Переключить тему",
    "eyebrow": f"ТОО «DARSA Solutions» · Қазақстан · БИН {BIN}",
    "h1": "Үш сөз.<br><em>Три программы<br>для дел, которые<br>у бизнеса уже есть.</em>",
    "sub": "Дүкен нужно считать. Той нужно собрать. В 1С нужно получить ответ. Мы не придумываем новые потребности, а закрываем те, что появились без нас.",
    "cta": "Смотреть продукты",
    "proof": [
        "iDüken от 15 990 ₸ в месяц",
        "касса работает без интернета",
        "қазақша және орысша",
    ],
    "band": [
        ("iDüken", "дүкен — магазин"),
        ("ToiApp", "той — праздник"),
        ("Bota", "Бота — қазақ есімі"),
    ],
    "reveal": "Магазин надо считать. На той надо найти зал и тамаду. В 1С надо получить ответ. Darsa делает ровно это, без лишних обещаний.",
    "iduken": {
        "gloss": "дүкен — магазин · розница",
        "lead": "Касса, склад и деньги магазина в одной программе. Видно, где заработали, а где потеряли.",
        "facts": [
            ("Касса не останавливается без интернета",
             "Чеки копятся на компьютере и уходят на сервер, как только связь вернётся. Смена закрывается одной суммой."),
            ("Склад ведётся сам",
             "Приход, списания, перемещения между точками, инвентаризация. Каждое движение остаётся в материальном отчёте."),
            ("Несколько точек в одном кабинете",
             "Товары и цены общие, остатки и выручка у каждой свои. Сотрудник видит свой магазин, владелец видит все."),
            ("Названия из Национального каталога",
             "Сканируете штрихкод, название подставляется из справочника НКТ по коду NTIN."),
        ],
        "price": "от <b>15 990 ₸</b> в месяц за точку · <b>89 990 ₸</b> за сеть до 10 точек",
        "btn": "Открыть iduken.kz",
    },
    "toiapp": {
        "gloss": "той — праздник · маркетплейс",
        "pill": "Готовится к запуску",
        "lead": "Всё для тоя в вашем городе. Ресторан, тамада, артисты, повара, фото и видео, ивент-агентства.",
        "facts": [
            ("Ищете там, где живёте",
             "Выбираете город и видите, кто работает рядом, от зала на 300 гостей до кавер-группы на вечер."),
            ("Свадьба, юбилей и любой другой той",
             "Площадка одна, а той у каждого свой. Фильтры собираются под ваш случай."),
            ("Договариваетесь напрямую",
             "Фото работ, цены и отзывы в анкете. Пишете исполнителю сами, без посредников."),
            ("Исполнителям тоже сюда",
             "Ресторан, тамада или студия размещают анкету и получают заявки из своего города."),
        ],
        "btn": "Узнать о запуске",
    },
    "bota": {
        "gloss": "Бота — қазақ есімі · ИИ-агент в 1С",
        "lead": "ИИ-агент, который живёт внутри вашей 1С. Спрашиваете словами, получаете данные, документы и объяснения.",
        "facts": [
            ("Отвечает по вашей базе",
             "«Сколько мы должны поставщикам на конец месяца?» Bota строит запрос к 1С и отвечает цифрой, а не ссылкой на отчёт."),
            ("Создаёт и заполняет документы",
             "Счёт, накладная, перемещение. Bota подготовит, бухгалтер проверит и проведёт."),
            ("Действует только там, где разрешено",
             "Права пользователя 1С остаются главными. Агент не видит и не меняет то, что закрыто для человека."),
            ("Работает с вашей конфигурацией",
             "Бухгалтерия, Управление торговлей, Розница и доработанные базы."),
        ],
        "btn": "Обсудить внедрение",
        "note": "Описание функций требует подтверждения владельца продукта.",
    },
    "steps_title": "Как начинается работа",
    "steps_lead": "Три шага, без долгих презентаций.",
    "steps": [
        ("Звонок на 20 минут", "Рассказываете, как устроен магазин или база. Мы говорим, подходит наш продукт или нет."),
        ("Настройка под ваш бизнес", "Заводим точки, товары и права сотрудников. Показываем на ваших данных, а не на демо-примере."),
        ("Работа и поддержка", "Отвечаем на казахском и русском. Обновления приходят сами, платить за них отдельно не нужно."),
    ],
    "about_title": "О компании",
    "about_lead": "Небольшая команда разработчиков в Казахстане.",
    "about_p": [
        "Мы делаем программы, которые работают в реальных условиях: когда в магазине пропал интернет, когда до тоя две недели, а тамады и зала ещё нет, когда бухгалтеру нужен ответ до обеда, а не отчёт на сорок страниц.",
        "Каждый продукт закрывает одну задачу целиком, а не десять задач наполовину.",
    ],
    "faq_title": "Вопросы, которые задают до оплаты",
    "faq_lead": "Если вашего вопроса тут нет, позвоните.",
    "faq": [
        ("Что будет с кассой, если пропал интернет?",
         "iDüken продолжает пробивать чеки. Они сохраняются на компьютере и уходят на сервер, как только связь вернётся. Смена закрывается одной суммой, расхождение видно сразу."),
        ("Сколько стоит iDüken?",
         "15 990 ₸ в месяц за одну точку. Для сети до десяти точек — 89 990 ₸ в месяц. Оплата в тенге, по договору с ТОО, счёт на юрлицо."),
        ("У меня три магазина. Их видно вместе?",
         "Да. Товары и цены общие, остатки и выручка считаются по каждой точке отдельно. Продавец видит только свой магазин, владелец — все сразу, в том числе с телефона."),
        ("Нужно ли вбивать названия товаров руками?",
         "Нет. Сканируете штрихкод, и название подставляется из справочника Национального каталога товаров по коду NTIN."),
        ("ToiApp уже можно пользоваться?",
         "Сервис готовится к запуску. Оставьте номер по телефону, и мы позовём, когда откроется ваш город. Исполнителям стоит записаться заранее."),
        ("Bota подключится к моей 1С?",
         "Bota работает с типовыми конфигурациями (Бухгалтерия, Управление торговлей, Розница) и с доработанными базами. Права пользователя остаются главными."),
    ],
    "final_h": "Позвоните и опишите свой случай.",
    "final_p": "Ответит человек из команды. Если задача не наша, скажем прямо и подскажем, к кому идти.",
    "final_btn": f"Позвонить {PHONE}",
    "footer": [
        ("Компания", "ТОО «DARSA Solutions»"),
        ("БИН", BIN),
        ("Страна", "Республика Казахстан"),
        ("Языки", "қазақша, русский"),
    ],
    "copyright": "© 2026 ТОО «DARSA Solutions» · iDüken · ToiApp · Bota",
    "top": "Наверх",
}

# --------------------------------------------------------------------------- KK
C["kk"] = {
    "title": "Darsa Solutions — iDüken, ToiApp, Bota",
    "desc": "«DARSA Solutions» ЖШС: iDüken — дүкеннің кассасы мен қоймасы, ToiApp — қалаңыздағы тойға керектің бәрі, Bota — 1С ішіндегі ЖИ-агент. Қазақстан, теңге, қазақша және орысша.",
    "og_title": "Darsa Solutions — Қазақстандағы бизнеске арналған бағдарламалар",
    "og_desc": "Дүкеннің кассасы мен қоймасы, тойға керектің бәрі, 1С ішіндегі ЖИ-агент.",
    "og_locale": "kk_KZ",
    "skip": "Мазмұнға өту",
    "nav_label": "Бөлімдер",
    "nav_faq": "Сұрақтар",
    "nav_call": "Қоңырау шалу",
    "lang_label": "Тіл",
    "theme_label": "Түсті тақырыпты ауыстыру",
    "eyebrow": f"«DARSA Solutions» ЖШС · Қазақстан · БСН {BIN}",
    "h1": "Үш сөз.<br><em>Бизнесте бұрыннан<br>бар істерге арналған<br>үш бағдарлама.</em>",
    "sub": "Дүкенді санау керек. Тойды жинау керек. 1С-тен жауап алу керек. Біз жаңа қажеттілік ойлап таппаймыз, бізсіз де пайда болғанын жабамыз.",
    "cta": "Өнімдерді көру",
    "proof": [
        "iDüken айына 15 990 ₸-ден",
        "касса интернетсіз де жұмыс істейді",
        "қазақша және орысша",
    ],
    "band": [
        ("iDüken", "дүкен · бөлшек сауда"),
        ("ToiApp", "той · мереке"),
        ("Bota", "Бота — қазақ есімі"),
    ],
    "reveal": "Дүкенді санау керек. Тойға зал мен асаба табу керек. 1С-тен жауап алу керек. Darsa дәл осыны істейді, артық уәдесіз.",
    "iduken": {
        "gloss": "дүкен · бөлшек сауда",
        "lead": "Дүкеннің кассасы, қоймасы және ақшасы бір бағдарламада. Қайдан таптық, қайдан жоғалттық — бәрі көрінеді.",
        "facts": [
            ("Касса интернетсіз тоқтамайды",
             "Чектер компьютерде жиналады да, байланыс қалпына келген бойда серверге жөнелтіледі. Ауысым бір сомамен жабылады."),
            ("Қойма өзі жүргізіледі",
             "Кіріс, есептен шығару, нүктелер арасындағы ауыстыру, түгендеу. Әр қозғалыс материалдық есепте қалады."),
            ("Бірнеше нүкте бір кабинетте",
             "Тауарлар мен бағалар ортақ, қалдық пен түсім әрқайсысында бөлек. Қызметкер өз дүкенін, иесі бәрін көреді."),
            ("Атаулар Ұлттық каталогтан",
             "Штрихкодты сканерлейсіз, атауы NTIN коды бойынша ҰТК анықтамалығынан қойылады."),
        ],
        "price": "айына бір нүкте үшін <b>15 990 ₸</b>-ден · 10 нүктеге дейінгі желі үшін <b>89 990 ₸</b>",
        "btn": "iduken.kz сайтын ашу",
    },
    "toiapp": {
        "gloss": "той · мереке · маркетплейс",
        "pill": "Іске қосуға дайындалып жатыр",
        "lead": "Қалаңыздағы тойға керектің бәрі. Мейрамхана, асаба, әртістер, аспаздар, фото және видео, ивент-агенттіктер.",
        "facts": [
            ("Өзіңіз тұратын жерден іздейсіз",
             "Қаланы таңдайсыз да, қасыңызда кім жұмыс істейтінін көресіз: 300 орындық залдан бір кештік кавер-топқа дейін."),
            ("Үйлену тойы, мерейтой және кез келген той",
             "Алаң біреу, той әркімнің өзінікі. Сүзгілер сіздің жағдайыңызға қарай жиналады."),
            ("Тікелей келісесіз",
             "Жұмыс суреттері, бағалар мен пікірлер анкетада. Орындаушыға өзіңіз жазасыз, делдалсыз."),
            ("Орындаушыларға да осында",
             "Мейрамхана, асаба немесе студия анкета орналастырып, өз қаласынан өтінім алады."),
        ],
        "btn": "Іске қосылу туралы білу",
    },
    "bota": {
        "gloss": "Бота — қазақ есімі · 1С ішіндегі ЖИ-агент",
        "lead": "Сіздің 1С-іңіздің ішінде тұратын ЖИ-агент. Сөзбен сұрайсыз, дерек, құжат және түсіндірме аласыз.",
        "facts": [
            ("Сіздің базаңыз бойынша жауап береді",
             "«Ай соңында жеткізушілерге қанша қарызбыз?» Bota 1С-ке сұраныс құрып, есепке сілтеме емес, нақты сан береді."),
            ("Құжаттарды жасап, толтырады",
             "Шот, жүкқұжат, ауыстыру. Bota дайындайды, бухгалтер тексеріп өткізеді."),
            ("Тек рұқсат етілген жерде әрекет етеді",
             "1С пайдаланушысының құқықтары басты болып қалады. Агент адамға жабық нәрсені көрмейді және өзгертпейді."),
            ("Сіздің конфигурацияңызбен жұмыс істейді",
             "Бухгалтерия, Сауданы басқару, Бөлшек сауда және пысықталған базалар."),
        ],
        "btn": "Енгізуді талқылау",
        "note": "Функциялар сипаттамасы өнім иесінің растауын талап етеді.",
    },
    "steps_title": "Жұмыс қалай басталады",
    "steps_lead": "Ұзақ презентациясыз үш қадам.",
    "steps": [
        ("20 минуттық қоңырау", "Дүкеннің не базаның қалай құрылғанын айтасыз. Біз өніміміз жарай ма, жоқ па — тура айтамыз."),
        ("Бизнесіңізге қарай баптау", "Нүктелерді, тауарларды және қызметкер құқықтарын енгіземіз. Демо-мысалда емес, сіздің деректеріңізде көрсетеміз."),
        ("Жұмыс және қолдау", "Қазақша және орысша жауап береміз. Жаңартулар өзі келеді, оларға бөлек төлеудің қажеті жоқ."),
    ],
    "about_title": "Компания туралы",
    "about_lead": "Қазақстандағы шағын әзірлеушілер командасы.",
    "about_p": [
        "Біз нақты жағдайда жұмыс істейтін бағдарлама жасаймыз: дүкенде интернет жоғалғанда, тойға екі апта қалып, асаба мен зал әлі табылмағанда, бухгалтерге қырық беттік есеп емес, түске дейінгі жауап керек болғанда.",
        "Әр өнім он істі жартылай емес, бір істі толық жабады.",
    ],
    "faq_title": "Төлемге дейін қойылатын сұрақтар",
    "faq_lead": "Сұрағыңыз мұнда болмаса, қоңырау шалыңыз.",
    "faq": [
        ("Интернет жоғалса, кассаға не болады?",
         "iDüken чек соғуын жалғастырады. Олар компьютерде сақталып, байланыс қалпына келген бойда серверге кетеді. Ауысым бір сомамен жабылады, айырма бірден көрінеді."),
        ("iDüken қанша тұрады?",
         "Бір нүкте үшін айына 15 990 ₸. Он нүктеге дейінгі желі үшін — айына 89 990 ₸. Төлем теңгемен, ЖШС-мен шарт бойынша, заңды тұлғаға шот жазылады."),
        ("Менде үш дүкен бар. Олар бірге көріне ме?",
         "Иә. Тауарлар мен бағалар ортақ, қалдық пен түсім әр нүкте бойынша бөлек есептеледі. Сатушы тек өз дүкенін, иесі бәрін бірден, оның ішінде телефоннан да көреді."),
        ("Тауар атауларын қолмен теру керек пе?",
         "Жоқ. Штрихкодты сканерлейсіз, атауы NTIN коды бойынша Ұлттық тауар каталогының анықтамалығынан қойылады."),
        ("ToiApp-ты қазір пайдалануға бола ма?",
         "Сервис іске қосуға дайындалып жатыр. Телефон арқылы нөміріңізді қалдырыңыз, қалаңыз ашылғанда шақырамыз. Орындаушыларға алдын ала тіркелген жөн."),
        ("Bota менің 1С-іме қосыла ма?",
         "Bota үлгілік конфигурациялармен (Бухгалтерия, Сауданы басқару, Бөлшек сауда) және пысықталған базалармен жұмыс істейді. Пайдаланушы құқықтары басты болып қалады."),
    ],
    "final_h": "Қоңырау шалып, жағдайыңызды айтыңыз.",
    "final_p": "Робот емес, команда адамы жауап береді. Міндет біздікі болмаса, тура айтып, кімге бару керегін айтамыз.",
    "final_btn": f"Қоңырау шалу {PHONE}",
    "footer": [
        ("Компания", "«DARSA Solutions» ЖШС"),
        ("БСН", BIN),
        ("Ел", "Қазақстан Республикасы"),
        ("Тілдер", "қазақша, орысша"),
    ],
    "copyright": "© 2026 «DARSA Solutions» ЖШС · iDüken · ToiApp · Bota",
    "top": "Жоғарыға",
}

# --------------------------------------------------------------------------- EN
C["en"] = {
    "title": "Darsa Solutions — iDüken, ToiApp, Bota",
    "desc": "DARSA Solutions LLP: iDüken runs a shop's till and stock, ToiApp gathers everything for a toi in your city, Bota is an AI agent inside 1C. Kazakhstan, tenge, Kazakh and Russian.",
    "og_title": "Darsa Solutions — software for business in Kazakhstan",
    "og_desc": "A shop's till and stock, everything for a toi, an AI agent inside 1C.",
    "og_locale": "en_US",
    "skip": "Skip to content",
    "nav_label": "Sections",
    "nav_faq": "Questions",
    "nav_call": "Call us",
    "lang_label": "Language",
    "theme_label": "Switch theme",
    "eyebrow": f"DARSA Solutions LLP · Kazakhstan · BIN {BIN}",
    "h1": "Three words.<br><em>Three programs<br>for work businesses<br>already do.</em>",
    "sub": "A shop has to be counted. A toi has to be put together. 1C has to give an answer. We don't invent new needs, we close the ones that were already there.",
    "cta": "See the products",
    "proof": [
        "iDüken from 15 990 ₸ a month",
        "the till works without internet",
        "Kazakh and Russian",
    ],
    "band": [
        ("iDüken", "düken — shop"),
        ("ToiApp", "toi — celebration"),
        ("Bota", "Bota — a Kazakh name"),
    ],
    "reveal": "A shop has to be counted. A toi needs a venue and a host. 1C has to give an answer. Darsa does exactly that, with no extra promises.",
    "iduken": {
        "gloss": "düken — shop · retail",
        "lead": "Till, stock and money in one program. You can see where you earned and where you lost.",
        "facts": [
            ("The till keeps working without internet",
             "Receipts pile up on the computer and reach the server the moment the connection is back. The shift closes with a single total."),
            ("Stock keeps itself",
             "Deliveries, write-offs, transfers between shops, stocktaking. Every movement stays in the stock report."),
            ("Several shops in one account",
             "Products and prices are shared, stock and revenue are counted per shop. Staff see their own shop, the owner sees all of them."),
            ("Names from the National Catalogue",
             "Scan a barcode and the name is filled in from the National Product Catalogue by its NTIN code."),
        ],
        "price": "from <b>15 990 ₸</b> a month per shop · <b>89 990 ₸</b> for a chain of up to 10",
        "btn": "Open iduken.kz",
    },
    "toiapp": {
        "gloss": "toi — a Kazakh celebration · marketplace",
        "pill": "Launching soon",
        "lead": "Everything for a toi in your city: venue, host, performers, cooks, photo and video, event agencies.",
        "facts": [
            ("Search where you live",
             "Pick your city and see who works nearby, from a hall for 300 guests to a cover band for the evening."),
            ("A wedding, an anniversary, any other toi",
             "The venue is one, but everyone's toi is their own. Filters follow your case."),
            ("Agree directly",
             "Photos of past work, prices and reviews in the profile. You message the vendor yourself, with no middleman."),
            ("Vendors belong here too",
             "A restaurant, a host or a studio posts a profile and receives requests from their own city."),
        ],
        "btn": "Ask about the launch",
    },
    "bota": {
        "gloss": "Bota — a Kazakh female name · AI agent in 1C",
        "lead": "An AI agent that lives inside your 1C. You ask in plain words and get data, documents and explanations.",
        "facts": [
            ("Answers from your own database",
             "“How much do we owe suppliers at the end of the month?” Bota builds the 1C query and answers with a number, not a link to a report."),
            ("Creates and fills in documents",
             "Invoice, delivery note, transfer. Bota prepares it, the accountant checks and posts it."),
            ("Acts only where it is allowed",
             "1C user rights stay in charge. The agent cannot see or change what is closed to the person."),
            ("Works with your configuration",
             "Accounting, Trade Management, Retail and customised databases."),
        ],
        "btn": "Discuss a rollout",
        "note": "Feature descriptions are pending confirmation by the product owner.",
    },
    "steps_title": "How work starts",
    "steps_lead": "Three steps, no long presentations.",
    "steps": [
        ("A 20 minute call", "You tell us how the shop or the database is set up. We say whether our product fits or not."),
        ("Setup for your business", "We add shops, products and staff permissions. We show it on your data, not on a demo."),
        ("Work and support", "We answer in Kazakh and Russian. Updates arrive on their own, with nothing extra to pay."),
    ],
    "about_title": "About the company",
    "about_lead": "A small development team in Kazakhstan.",
    "about_p": [
        "We build software that holds up in real conditions: when the shop loses its internet, when the toi is two weeks away and there is still no host or venue, when the accountant needs an answer before lunch rather than a forty page report.",
        "Each product closes one job completely instead of ten jobs halfway.",
    ],
    "faq_title": "Questions people ask before paying",
    "faq_lead": "If your question isn't here, call us.",
    "faq": [
        ("What happens to the till when the internet drops?",
         "iDüken keeps printing receipts. They are stored on the computer and sent to the server as soon as the connection is back. The shift closes with a single total and any discrepancy is visible straight away."),
        ("What does iDüken cost?",
         "15 990 ₸ a month for one shop. For a chain of up to ten shops, 89 990 ₸ a month. Paid in tenge, under a contract with the LLP, invoiced to the company."),
        ("I have three shops. Can I see them together?",
         "Yes. Products and prices are shared, while stock and revenue are counted per shop. A salesperson sees only their own shop, the owner sees all of them, including from a phone."),
        ("Do I have to type product names by hand?",
         "No. Scan a barcode and the name is filled in from the National Product Catalogue of Kazakhstan by its NTIN code."),
        ("Can I use ToiApp already?",
         "The service is getting ready to launch. Leave your number by phone and we will call when your city opens. Vendors are better off signing up in advance."),
        ("Will Bota connect to my 1C?",
         "Bota works with the standard configurations (Accounting, Trade Management, Retail) and with customised databases. User rights stay in charge."),
    ],
    "final_h": "Call and tell us your case.",
    "final_p": "A person from the team answers. If the job isn't ours, we will say so and point you to someone who can help.",
    "final_btn": f"Call {PHONE}",
    "footer": [
        ("Company", "DARSA Solutions LLP"),
        ("BIN", BIN),
        ("Country", "Republic of Kazakhstan"),
        ("Languages", "Kazakh, Russian"),
    ],
    "copyright": "© 2026 DARSA Solutions LLP · iDüken · ToiApp · Bota",
    "top": "Back to top",
}
